services:
  botdiscord-cobrao:
    build: .
    container_name: botdiscord-cobrao
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
